### ISSUE TITLE
图片丢失

### ISSUE THREAD

**Issue by Sichongzou** [DrinkOolongTea/splatoon2-bot#3]
今天我的Bot在跑这个插件的时候，在生成打工图片时出现了错误。错误为图片丢失，具体目录为 splatoon2_tools\resource\Random_Rare.png
我没有在仓库中看到这个文件，不知道是否是作者忘记添加这张图片了，还是wiki上有新的页面更新。

**Comment by DrinkOolongTea** [comment]
好像确实没有这个图片，这个能具体到哪一块么 打工还是凃地里面的

**Comment by DrinkOolongTea** [comment]
我看到了，应该是随机金问号的问题，我从官网获取图的时候他命名不是这个，临时解决可以在python包 我这个插件下面，把Random_2.png这个名字改成Random_Rare.png就行了，问题也可能发生在普通问号，这个只能等wiki刷新普通问号工的时候才能知道

**Comment by DrinkOolongTea** [comment]
pip安装的话 /python3.9/site-packages/splatoon2_tools/resource大概是这个位置

**Comment by Sichongzou** [comment]
好的，我会将Random_2.png复制一份并重命名为Random_Rare.png来解决这个问题，如果有其他情况我会提交iss。
很高兴能得到您的答复。

**Comment by DrinkOolongTea** [comment]
好 多谢 如果没什么问题的话可以吧这个iss关闭，顺便提一嘴 五一打工4金问号，这不冲爆

**Comment by Sichongzou** [comment]
冲！！！！！
