### ISSUE TITLE
时间错误。

### ISSUE THREAD

**Issue by Sichongzou** [DrinkOolongTea/splatoon2-bot#4]
我在实际使用的过程中，发现打工时间错误，我一直以为是Wiki上的错误，结果仔细对比后，发现是程序错误。我发现在网页抓取的时候，默认会显示UTC时间，这和我们所常用的时间是有时间差异的。正常情况下，程序应该都没有问题，但是当出现第二天的情况，比如打工时间结束刚好是00:00的时候，理论上日期已经是第二天了，但是日期并没有变化。

**Comment by DrinkOolongTea** [comment]
是否是用docker部署 如果是docker部署的话 是时区问题 要改docker容器时区 可以看下我readme

**Comment by Sichongzou** [comment]
我直接下载了 Github上的源码丢进了我的plugins下

**Comment by Sichongzou** [comment]
您试着用您的Bot返回打工图片试试看，这次打工正常应该是五月三号00:00结束，您那边是正确的嘛

**Comment by DrinkOolongTea** [comment]
哦 我理解错了 我稍等看一下

**Comment by Sichongzou** [comment]
这个应该是调整时差的时候，没有考虑进日期导致的，也许可以打表将所有的英文日期全部改为数字？

**Comment by DrinkOolongTea** [comment]
就是因为抓取到的是文本型的utc时间，没法直接转时间戳 英文也是原文，你说的那个问题我想办法改一下

**Comment by Sichongzou** [comment]
试着直接打表试试看，比如抓到May直接转成5？

**Comment by DrinkOolongTea** [comment]
bug已在1.3.1版本修复（我是sb，python支持英文日期转数字）

**Comment by Sichongzou** [comment]
我已经移植了部分代码，现在我的程序是正确的，很感谢您维护相关代码。稍后我将关闭该Issues
