### ISSUE TITLE
功能寄了 功能寄了

### ISSUE THREAD

**Issue by Sichongzou** [DrinkOolongTea/splatoon2-bot#7]
从早上6点左右 功能全部失效，怀疑是wiki页面变动，你的bot运行是完美的嘛

**Comment by DrinkOolongTea** [comment]
刚刚看了看 wiki页面是变动了 要改一下抓取逻辑，现在页面逻辑变得有点怪，我临时修改了一版 先凑合用吧，你可以看下core.py get_salmon_xxxx这几个方法 改动了这几个地方
